### ISSUE TITLE
NPM Error - New

### ISSUE THREAD

**Issue by scottbakernc** [subdigital/kv-downloader#2]
Anyone have a fix for the error that happens now trying to use this tool? I've tried every fix I can find across forums and nothing seems to resolve the issue. Thanks!

![Screenshot 2024-09-11 at 11 45 47 AM](https://github.com/user-attachments/assets/a52a791e-1cd8-4db8-86f4-3cb67e140fff)

**Comment by geebeetoo** [comment]
I did get that error as well. I discovered I did not need to run npm. You got this form the YouTube video but that is the old version of kv-downloader

now all you need to do is:
1) download the code
2) Got to release page (see link below) and get the appropriate file for your platform. And add it in your PATH.
https://github.com/subdigital/kv-downloader/releases

That is all. Then you can run command "kv_downloader" auth to get going.

**Comment by scottbakernc** [comment]
> I did get that error as well. I discovered I did not need to run npm. You got this form the YouTube video but that is the old version of kv-downloader
> 
> now all you need to do is:
> 
> 1. download the code
> 2. Got to release page (see link below) and get the appropriate file for your platform. And add it in your PATH.
>    https://github.com/subdigital/kv-downloader/releases
> 
> That is all. Then you can run command "kv_downloader" auth to get going.

Thanks! I run this on a Mac so I don't know how to do Step 1 really. I had a colleague help that was good using Terminal to get it all working.

**Comment by scottbakernc** [comment]
I've got it setup and running, but the instructions for the command give me errors. For example, I used this:

kv_downloader https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html

and get "error: unrecognized subcommand"

**Comment by geebeetoo** [comment]
> I've got it setup and running, but the instructions for the command give me errors. For example, I used this:
> 
> kv_downloader https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html
> 
> and get "error: unrecognized subcommand"

Your command is incomplete.

use:
kv_downloader download  "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"

please note that the song URL must be within double quotes.

if you need to include the count in, then here's how:
kv_downloader download  --count-in "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"

if you want to change the pitch say down 1:
kv_downloader download  --transpose=-1 "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"

up 2:
kv_downloader download  --transpose=2 "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"

say you want the count in and transpose
kv_downloader download  --count-in  --transpose=2 "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"

hope this helps

**Comment by scottbakernc** [comment]
> > I've got it setup and running, but the instructions for the command give me errors. For example, I used this:
> > kv_downloader https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html
> > and get "error: unrecognized subcommand"
> 
> Your command is incomplete.
> 
> use: kv_downloader download "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"
> 
> please note that the song URL must be within double quotes.
> 
> if you need to include the count in, then here's how: kv_downloader download --count-in "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"
> 
> if you want to change the pitch say down 1: kv_downloader download --transpose=-1 "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"
> 
> up 2: kv_downloader download --transpose=2 "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"
> 
> say you want the count in and transpose kv_downloader download --count-in --transpose=2 "https://www.karaoke-version.com/custombackingtrack/joe-cocker/with-a-little-help-from-my-friends-live.html"
> 
> hope this helps

Thanks! These are the examples I was needing. I appreciate it and thank you so much!
